--CREATE DATABASE PastelariaSMN

USE PastelariaSMN

CREATE TABLE Administrador(
    IdAdmin TINYINT PRIMARY KEY IDENTITY,
    Email VARCHAR(50) NOT NULL UNIQUE,
    Senha VARCHAR(50) NOT NULL
)

CREATE TABLE Usuario (
	IdUsuario SMALLINT PRIMARY KEY IDENTITY,
	Nome VARCHAR(30)  NOT NULL,
	Sobrenome VARCHAR(50)  NOT NULL,
	DataNascimento DATE  NOT NULL,
	Senha VARCHAR(50) NOT NULL,
	EGestor BIT NOT NULL,
	EstaAtivo BIT NOT NULL,

	IdGestor SMALLINT FOREIGN KEY (IdGestor) REFERENCES Usuario
)

CREATE TABLE Email (
	IdEmail SMALLINT PRIMARY KEY IDENTITY,
	EnderecoEmail VARCHAR(254) NOT NULL,
	IdUsuario SMALLINT NOT NULL FOREIGN KEY (IdUsuario) REFERENCES Usuario
)

CREATE TABLE Endereco (
	IdEndereco SMALLINT PRIMARY KEY IDENTITY,
	Rua VARCHAR(70) NOT NULL,
	Bairro VARCHAR(60) NOT NULL,
	Numero VARCHAR(10),
	Complemento VARCHAR(50),
	CEP VARCHAR(8) NOT NULL,
	Cidade VARCHAR(32) NOT NULL,
	UF VARCHAR(2) NOT NULL,
	IdUsuario SMALLINT NOT NULL FOREIGN KEY (IdUsuario) REFERENCES Usuario
)

CREATE TABLE TipoTelefone (
	IdTipoTelefone TINYINT PRIMARY KEY IDENTITY,
	Tipo VARCHAR(20) NOT NULL
)

CREATE TABLE Telefone (
	IdTelefone SMALLINT PRIMARY KEY IDENTITY,
	Numero INT NOT NULL,
	DDD TINYINT NOT NULL,
	IdUsuario SMALLINT NOT NULL FOREIGN KEY (IdUsuario) REFERENCES Usuario,
	IdTipoTelefone TINYINT NOT NULL FOREIGN KEY (IdTipoTelefone) REFERENCES TipoTelefone
)

CREATE TABLE StatusTarefa (
	IdStatusTarefa TINYINT PRIMARY KEY IDENTITY,
	Nome VARCHAR(20) NOT NULL
)

CREATE TABLE Tarefa (
	IdTarefa SMALLINT PRIMARY KEY IDENTITY,
	--Titulo VARCHAR(50) NOT NULL,
	Descricao VARCHAR(300) NOT NULL,
	DataCadastro DATETIME DEFAULT GETDATE(),
	DataLimite DATETIME NOT NULL,
	DataConclusao DATETIME,
	EstaCancelada BIT NOT NULL DEFAULT 0,
	
	IdGestor SMALLINT NOT NULL FOREIGN KEY (IdGestor) REFERENCES Usuario,
	IdSubordinado SMALLINT NOT NULL FOREIGN KEY (IdSubordinado) REFERENCES Usuario,
	IdStatusTarefa TINYINT NOT NULL FOREIGN KEY (IdStatusTarefa) REFERENCES StatusTarefa
)

CREATE TABLE Comentario (
	IdComentario SMALLINT PRIMARY KEY IDENTITY,
	Descricao VARCHAR(200) NOT NULL,
	IdTarefa SMALLINT NOT NULL FOREIGN KEY (IdTarefa) REFERENCES Tarefa

)
